POST http://localhost:8000/user/login
Content-Type: application/javascript

{
    "email": "musa@gmail.com",
    "password": "123456"
}

###
get http://localhost:8000/profile/booking-details/5f2cdea948301f015c858edb

